# Generated by Django 5.0.4 on 2024-04-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_remove_post_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
