# Generated by Django 5.0.4 on 2024-04-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_post_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
