# Generated by Django 5.0.4 on 2024-04-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0009_alter_post_options_alter_post_image_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("post", models.ManyToManyField(to="post.post")),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "db_table": "tag",
                "ordering": ["title"],
            },
        ),
    ]
