# Generated by Django 5.0.4 on 2024-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0010_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="post.tag"),
        ),
    ]
